### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by Jasper-Bekkers** [chris-morgan/anymap#43] opened 2022-01-24 14:18 UTC
Hi, @chris-morgan could you or somebody else involved in this project please publish a new release on crates.io, or possibly hand over maintainership of this project to somebody that can publish new releases?

**Comment by chris-morgan** [comment] 2022-01-24 14:23
Sigh. I’ve been holding off on this vastly too long. Years too long. I’ve had this in mind specifically for the last few weeks while returning to slightly more productiony Rust and crate stuff (for much of the last few years I’ve been using Rust only for personal stuff that I didn’t intend to share), and I hear your plea. I intend to tidy everything up and make a release tomorrow, within 24 hours. But for now, goodnight!

(Duplicate of #37, but I understand and apologise.)

**Comment by Jasper-Bekkers** [comment] 2022-01-25 00:32
Made a duplicate kind of on purpose hoping it would reach your inbox 😅.

Good to hear you're getting back into production with Rust stuff, if you ever feel like maintaining this becomes a bit of a burden, feel free to tag me and I can see how to help you out.

I've personally really liked using cargo-release to quickly spin new releases without much fuss.

Hope you don't mind the ping,

 - Jasper

**Comment by chris-morgan** [comment] 2022-01-25 13:25
anymap 1.0.0-beta.1 published. I spent a *lot* longer on it than I expected to, and there are some fairly significant internal changes, though the external are mostly very straightforward. Let me know what you reckon. I’ll leave it for a week, then publish 1.0.0 if nothing seems awry.

**Closed by chris-morgan** 2022-01-25 13:25 UTC
